services:
  mattermost:
    image: mattermost/mattermost-team-edition:11.5.1
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8065
      - ${PANEL_APP_PORT_CALLS}:8443/udp
      - ${PANEL_APP_PORT_CALLS}:8443/tcp
    security_opt:
      - no-new-privileges:true
    read_only: ${MATTERMOST_CONTAINER_READONLY}
    tmpfs:
      - /tmp
    volumes:
      - ./data/config:/mattermost/config:rw
      - ./data/data:/mattermost/data:rw
      - ./data/logs:/mattermost/logs:rw
      - ./data/plugins:/mattermost/plugins:rw
      - ./data/client/plugins:/mattermost/client/plugins:rw
      - ./data/bleve:/mattermost/bleve-indexes:rw
    environment:
      - TZ=${TZ}
      - MM_SQLSETTINGS_DRIVERNAME=${MM_SQLSETTINGS_DRIVERNAME}
      - MM_SQLSETTINGS_DATASOURCE=${MM_SQLSETTINGS_DRIVERNAME}://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=${MM_BLEVESETTINGS_INDEXDIR}
      - MM_SERVICESETTINGS_SITEURL=${MM_SERVICESETTINGS_SITEURL}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
