services:
  frpc:
    image: snowdreamtech/frpc:0.69.1
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - ./data:/etc/frp
    labels:
      createdBy: "Apps"
