#!/bin/bash

set -euo pipefail

BASE_DIR=$(cd "$(dirname "$0")/.." && pwd)
DATA_DIR="${BASE_DIR}/data"
CONFIG_FILE="${DATA_DIR}/config.toml"

require_env() {
    local name="$1"
    if [ -z "${!name:-}" ]; then
        echo "missing required env: ${name}" >&2
        exit 1
    fi
}

require_env MEMOH_ADMIN_USERNAME
require_env MEMOH_ADMIN_PASSWORD
require_env MEMOH_ADMIN_EMAIL
require_env MEMOH_JWT_SECRET
require_env POSTGRES_PASSWORD
require_env MEMOH_TIMEZONE

mkdir -p \
    "${DATA_DIR}" \
    "${DATA_DIR}/postgres" \
    "${DATA_DIR}/containerd" \
    "${DATA_DIR}/cni" \
    "${DATA_DIR}/memoh" \
    "${DATA_DIR}/qdrant"

REGISTRY_LINE='# registry = "docker.1ms.run"'
if [ -n "${MEMOH_WORKSPACE_REGISTRY:-}" ]; then
    REGISTRY_LINE="registry = \"${MEMOH_WORKSPACE_REGISTRY}\""
fi

cat >"${CONFIG_FILE}" <<EOF
## Generated by 1Panel Memoh app package
[log]
level = "info"
format = "text"

[server]
addr = "server:8080"

[admin]
username = "${MEMOH_ADMIN_USERNAME}"
password = "${MEMOH_ADMIN_PASSWORD}"
email = "${MEMOH_ADMIN_EMAIL}"

[auth]
jwt_secret = "${MEMOH_JWT_SECRET}"
jwt_expires_in = "168h"

timezone = "${MEMOH_TIMEZONE}"

[containerd]
socket_path = "/run/containerd/containerd.sock"
namespace = "default"

[workspace]
${REGISTRY_LINE}
default_image = "debian:bookworm-slim"
snapshotter = "overlayfs"
data_root = "/opt/memoh/data"
runtime_dir = "/opt/memoh/runtime"

[postgres]
host = "postgres"
port = 5432
user = "memoh"
password = "${POSTGRES_PASSWORD}"
database = "memoh"
sslmode = "disable"

[qdrant]
base_url = "http://qdrant:6334"
api_key = ""
timeout_seconds = 10

[sparse]
base_url = "http://sparse:8085"

[browser_gateway]
host = "browser"
port = 8083
server_addr = "server:8080"

[web]
host = "127.0.0.1"
port = 8082
EOF

chmod 600 "${CONFIG_FILE}"
