services:
  rsshub:
    image: diygod/rsshub
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:1200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1200/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - 1panel-network
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://${PANEL_REDIS_PASSWORD}@${PANEL_REDIS_HOST}:${PANEL_REDIS_PORT}/"
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000"
    depends_on:
      - browserless

  browserless:
    image: browserless/chrome
    restart: always
    ulimits:
      core:
        hard: 0
        soft: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
