version: "3"

services:
  ${CONTAINER_NAME}:
    image: t8y2/dbx:${PANEL_APP_VERSION_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PANEL_APP_PORT_HTTP}:4224
    environment:
      - DBX_PASSWORD=${PANEL_DB_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
