version: "3"

services:
  talebook:
    image: talebook/talebook:v26.06.29
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data:/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
      - ${PANEL_APP_PORT_HTTPS}:443
    environment:
      - PUID=${TALEBOOK_PUID}
      - PGID=${TALEBOOK_PGID}
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
