services:
  dbx:
    image: t8y2/dbx:0.5.59
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      - DBX_PASSWORD=${PANEL_DB_PASSWORD}
    ports:
      - "${PANEL_APP_PORT_HTTP}:4224"
    volumes:
      - ./data:/app/data
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
