services:
  upage:
    image: halohub/upage:2.0.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      LLM_PROVIDER: ${LLM_PROVIDER}
      PROVIDER_API_KEY: ${PROVIDER_API_KEY}
      PROVIDER_BASE_URL: ${PROVIDER_BASE_URL}
      LLM_DEFAULT_MODEL: ${LLM_DEFAULT_MODEL}
      LLM_MINOR_MODEL: ${LLM_MINOR_MODEL}
      LLM_VISION_PROVIDER: ${LLM_VISION_PROVIDER}
      LLM_VISION_MODEL: ${LLM_VISION_MODEL}
      VISION_PROVIDER_BASE_URL: ${VISION_PROVIDER_BASE_URL}
      VISION_PROVIDER_API_KEY: ${VISION_PROVIDER_API_KEY}
      SERPER_API_KEY: ${SERPER_API_KEY}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB}
      USAGE_LOG_FILE: "true"
      OPERATING_ENV: production
      LOG_LEVEL: debug
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./storage:/app/storage
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
