services:
  easytier:
    image: easytier/easytier:v2.6.1
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    privileged: ${PRIVILEGED_MODE}
    hostname: ${HOSTNAME}
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ./data/data:/root
      - ./data/config.toml:/root/config.toml
    command: ${COMMAND}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
