services:
  linkding:
    image: sissbruecker/linkding:1.45.0-plus
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data:/etc/linkding/data
    ports:
      - "${PANEL_APP_PORT_HTTP}:9090"
    environment:
      LD_SUPERUSER_NAME: ${ADMIN_USERNAME}
      LD_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
